version: '3'

services:
  mailcatcher:
    image: tophfr/mailcatcher:0.6.5
    restart: always
    environment:
    - VIRTUAL_HOST=${MAILCATCHER_VIRTUAL_HOST:-mail.docker.local}
    networks:
    - localhost
