version: '3'

services:
  mysql:
    image: centos/mysql-57-centos7
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
    volumes:
    - mysql:/var/lib/mysql/data
    networks:
    - dbaas

  adminer:
    image: adminer
    restart: always
    environment:
    - VIRTUAL_HOST=${ADMINER_VIRTUAL_HOST:-adminer.dbaas.local}
    - VIRTUAL_PORT=8080
    networks:
    - proxy
    - dbaas

networks:
  dbaas:
    external: true
  proxy:
    external: true

volumes:
  mysql: